# Generated by Django 5.2.1 on 2025-05-14 19:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Prop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Lights', 'Lights'), ('Tables', 'Tables'), ('Banners', 'Banners'), ('Costumes', 'Costumes')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('condition', models.CharField(choices=[('Good', 'Good'), ('Fair', 'Fair'), ('Damaged', 'Damaged')], max_length=10)),
                ('storage_location', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UsageLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
                ('date_of_use', models.DateField()),
                ('quantity_used', models.PositiveIntegerField()),
                ('return_status', models.CharField(choices=[('Returned', 'Returned'), ('Damaged', 'Damaged'), ('Missing', 'Missing')], max_length=10)),
                ('prop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.prop')),
            ],
        ),
    ]
