# Generated by Django 5.2.1 on 2025-05-14 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prop',
            name='category',
            field=models.CharField(choices=[('Lights', 'Lights'), ('Tables', 'Tables'), ('Banners', 'Banners'), ('Costumes', 'Costumes'), ('Others', 'Others')], max_length=20),
        ),
    ]
