# Generated by Django 5.2.1 on 2025-05-15 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_borrower_propuse'),
    ]

    operations = [
        migrations.AddField(
            model_name='propuse',
            name='used_by_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
