# Generated by Django 5.2.1 on 2025-05-15 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_propuse_used_by_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='prop',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='prop_images/'),
        ),
    ]
